type Props = {
  alerts: any[];
  busyAlertId?: string | null;
  onMarkAsRead?: (alertId: string) => void;
  onResolve?: (alertId: string) => void;
};

function severityClasses(severity: string) {
  switch (severity) {
    case "critical":
      return "bg-red-500/15 text-red-300 border-red-500/30";
    case "high":
      return "bg-orange-500/15 text-orange-300 border-orange-500/30";
    case "medium":
      return "bg-yellow-500/15 text-yellow-300 border-yellow-500/30";
    default:
      return "bg-emerald-500/15 text-emerald-300 border-emerald-500/30";
  }
}

export function RecentAlertsPanel({
  alerts,
  busyAlertId,
  onMarkAsRead,
  onResolve,
}: Props) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-xl">
      <div className="mb-5 flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-white">Recent alerts</h3>
          <p className="text-sm text-slate-400">
            Latest prevention events generated by the engine.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {alerts.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-slate-400">
            No alerts found yet.
          </div>
        ) : (
          alerts.map((alert) => {
            const isBusy = busyAlertId === alert.id;
            const isResolved = alert.status === "resolved";

            return (
              <div
                key={alert.id}
                className="rounded-2xl border border-white/10 bg-black/20 p-4"
              >
                <div className="mb-3 flex items-start justify-between gap-3">
                  <div>
                    <h4 className="text-sm font-semibold text-white">
                      {alert.title}
                    </h4>
                    <p className="mt-1 text-sm text-slate-400">
                      {alert.description}
                    </p>
                  </div>

                  <span
                    className={`rounded-full border px-2.5 py-1 text-xs font-medium capitalize ${severityClasses(
                      alert.severity
                    )}`}
                  >
                    {alert.severity}
                  </span>
                </div>

                <div className="mb-4 flex flex-wrap gap-2 text-xs text-slate-400">
                  <span className="rounded-full border border-white/10 px-2.5 py-1">
                    Status: {alert.status}
                  </span>
                  <span className="rounded-full border border-white/10 px-2.5 py-1">
                    Priority: {alert.priority}
                  </span>
                  <span className="rounded-full border border-white/10 px-2.5 py-1">
                    Action: {alert.recommended_action}
                  </span>
                  <span className="rounded-full border border-white/10 px-2.5 py-1">
                    Read: {alert.is_read ? "Yes" : "No"}
                  </span>
                </div>

                <div className="flex flex-wrap gap-3">
                  <button
                    type="button"
                    disabled={isBusy || alert.is_read}
                    onClick={() => onMarkAsRead?.(alert.id)}
                    className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-white transition hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {isBusy ? "Updating..." : alert.is_read ? "Read" : "Mark as read"}
                  </button>

                  <button
                    type="button"
                    disabled={isBusy || isResolved}
                    onClick={() => onResolve?.(alert.id)}
                    className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-sm text-emerald-300 transition hover:bg-emerald-500/20 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {isBusy ? "Updating..." : isResolved ? "Resolved" : "Resolve"}
                  </button>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}